spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: mysql0000ffFF
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 7200 # 2h
    refreshTokenExpiration: 604800 # 7d


